#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 15 16:54:02 EEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.2.2 + EuphoriaPatches_1.3.2
enableShaders=true
